DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CentreSummaryViewModel.cs
namespace DigitalLearningSolutions.Web.ViewModels.SuperAdmin.Centres
{
    using DigitalLearningSolutions.Data.Models.Centres;

    public class CentreSummaryViewModel
    {
        public CentreSummaryViewModel(CentreSummaryForSuperAdmin model)
        {
            CentreId = model.CentreId;
            CentreName = model.CentreName;
            RegionName = model.RegionName;
            ContactForename = model.ContactForename;
            ContactSurname = model.ContactSurname;
            ContactEmail = model.ContactEmail;
            ContactTelephone = model.ContactTelephone;
            CentreType = model.CentreType;
            Active = model.Active;
        }

        public int CentreId { get; set; }
        public string CentreName { get; set; }
        public string RegionName { get; set; }
        public string? ContactForename { get; set; }
        public string? ContactSurname { get; set; }
        public string? ContactEmail { get; set; }
        public string? ContactTelephone { get; set; }
        public string CentreType { get; set; }
        public bool Active { get; set; }
    }
}

DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/CentresViewModel.cs
namespace DigitalLearningSolutions.Web.ViewModels.SuperAdmin.Centres
{
    using DigitalLearningSolutions.Data.Helpers;
    using DigitalLearningSolutions.Data.Models.Centres;
    using DigitalLearningSolutions.Data.Models.SearchSortFilterPaginate;
    using DigitalLearningSolutions.Web.ViewModels.Common.SearchablePage;
    using System.Collections.Generic;
    using System.Linq;

    public class CentresViewModel : BaseSearchablePageViewModel<CentreEntity>
    {
        public CentresViewModel(SearchSortFilterPaginationResult<CentreEntity> result) : base(
            result,
            true,
            null,
            "Search centre"
        )
        {
            Centres = result.ItemsToDisplay.Select(
                centre => new SearchableCentreViewModel(
                    centre,
                    result.GetReturnPageQuery($"{centre.Centre.CentreId}-card")
                )
            );
        }

        public string Search { get; set; }
        public int Region { get; set; }
        public int CentreType { get; set; }
        public int ContractType { get; set; }
        public string CentreStatus { get; set; }
        public IEnumerable<SearchableCentreViewModel> Centres { get; set; }
        public override IEnumerable<(string, string)> SortOptions { get; } = new[]
        {
            DefaultSortByOptions.Name,
        };

        public override bool NoDataFound => !Centres.Any() && NoSearchOrFilter;
    }
}

DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/EditCentreDetailsSuperAdminViewModel.cs
namespace DigitalLearningSolutions.Web.ViewModels.SuperAdmin.Centres
{
    using DigitalLearningSolutions.Data.Models.Centres;
    using DigitalLearningSolutions.Web.Attributes;
    using System.ComponentModel.DataAnnotations;

    public class EditCentreDetailsSuperAdminViewModel
    {
        public EditCentreDetailsSuperAdminViewModel() { }

        public EditCentreDetailsSuperAdminViewModel(Centre centre)
        {
            CentreId = centre.CentreId;
            CentreName = centre.CentreName;
            CentreTypeId = centre.CentreTypeId;
            CentreType = centre.CentreType;
            RegionName = centre.RegionName;
            CentreEmail = centre.CentreEmail;
            IpPrefix = centre.IpPrefix;
            ShowOnMap = centre.ShowOnMap;
            RegionId = centre.RegionId;
        }

        public int CentreId { get; set; }
        [Required(ErrorMessage = "Enter a centre name")]
        public string CentreName { get; set; }
        public int CentreTypeId { get; set; }
        public string? CentreType { get; set; }
        public int RegionId { get; set; }
        public string? RegionName { get; set; }
        [MaxLength(250, ErrorMessage = "Email must be 250 characters or fewer")]
        [EmailAddress(ErrorMessage = "Enter an email in the correct format, like name@example.com")]
        [NoWhitespace(ErrorMessage = "Email must not contain any whitespace characters")]
        public string? CentreEmail { get; set; }
        public string? IpPrefix { get; set; }
        public bool ShowOnMap { get; set; }
    }
}

DigitalLearningSolutions.Web/ViewModels/SuperAdmin/Centres/SearchableCentreViewModel.cs
namespace DigitalLearningSolutions.Web.ViewModels.SuperAdmin.Centres
{
    using DigitalLearningSolutions.Data.Models.Centres;
    using DigitalLearningSolutions.Data.Models.SearchSortFilterPaginate;
    using DigitalLearningSolutions.Web.ViewModels.Common.SearchablePage;

    public class SearchableCentreViewModel : BaseFilterableViewModel
    {
        public SearchableCentreViewModel(
            CentreEntity centre,
            ReturnPageQuery returnPageQuery
        )
        {
            CentreId = centre.Centre.CentreId;
            CentreName = centre.Centre.CentreName;
            RegionName = centre.Regions.RegionName;
            ContactForename = centre.Centre.ContactForename;
            ContactSurname = centre.Centre.ContactSurname;
            ContactEmail = centre.Centre.ContactEmail;
            ContactTelephone = centre.Centre.ContactTelephone;
            CentreType = centre.CentreTypes.CentreType;
            Active =centre.Centre.Active;
            ReturnPageQuery = returnPageQuery;
        }

        public int CentreId { get; set; }
        public string CentreName { get; set; }
        public string RegionName { get; set; }
        public string? ContactForename { get; set; }
        public string? ContactSurname { get; set; }
        public string? ContactEmail { get; set; }
        public string? ContactTelephone { get; set; }
        public string CentreType { get; set; }
        public bool Active { get; set; }
        public ReturnPageQuery ReturnPageQuery { get; set; }
    }
}

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdminRoleInputs.cs
namespace DigitalLearningSolutions.Web.ViewModels.TrackingSystem.Centre.Administrator
{
    using DigitalLearningSolutions.Web.Models.Enums;
    using DigitalLearningSolutions.Web.ViewModels.Common.ViewComponents;
    using NHSUKViewComponents.Web.ViewModels;

    public class AdminRoleInputs
    {
        public static CheckboxListItemViewModel CentreAdminCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsCentreAdmin),
            "Centre administrator",
            "Manage delegates, courses and course groups. Enrol users on courses. View reports."
        );

        public static CheckboxListItemViewModel CentreManagerCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsCenterManager),
            "Centre manager",
            "Manages user access permissions for administrators at the centre, sees all support tickets for the centre in addition to having all of the permissions of a centre administrator."
        );

        public static CheckboxListItemViewModel SupervisorCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsSupervisor),
            "Supervisor",
            "Oversees individual and groups of delegates. Assigns and reviews self-assessments. Arranges supervision sessions."
        );

        public static CheckboxListItemViewModel NominatedSupervisorCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsNominatedSupervisor),
            "Nominated supervisor",
            "Confirms self-assessment results for learners."
        );

        public static CheckboxListItemViewModel TrainerCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsTrainer),
            "Trainer",
            "Delivers face to face or online training sessions and records attendance. Not yet implemented in the system."
        );

        public static CheckboxListItemViewModel ContentCreatorCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsContentCreator),
            "Content Creator licence",
            "Assigned a Content Creator licence number and has access to download and install Content Creator in CMS."
        );

        public static CheckboxListItemViewModel SuperAdministratorCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsSuperAdmin),
            "Super administrator",
            "Access to the super admin interface to manage access to the platform and respond to support tickets"
        );

        public static CheckboxListItemViewModel ReportViewerCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsReportViewer),
            "Report viewer",
            "View additional system reports above and beyond those visible to standard administrators"
        );

        public static CheckboxListItemViewModel LocalWorkforceManagerCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsLocalWorkforceManager),
            "Local workforce manager",
            "Manages competency profiles for the organisation"
        );

        public static CheckboxListItemViewModel FrameworkDeveloperCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsFrameworkDeveloper),
            "Framework developer",
            "Creates and manages competency frameworks"
        );

        public static CheckboxListItemViewModel WorkforceManagerCheckbox = new CheckboxListItemViewModel(
            nameof(EditRolesViewModel.IsWorkforceManager),
            "Workforce manager",
            "Manages national competency profiles"
        );

        public static RadiosListItemViewModel NoCmsPermissionsRadioButton = new RadiosListItemViewModel(
            ContentManagementRole.NoContentManagementRole,
            "No CMS permissions"
        );

        public static RadiosListItemViewModel CmsAdministratorRadioButton = new RadiosListItemViewModel(
            ContentManagementRole.CmsAdministrator,
            "CMS administrator",
            "Create bespoke courses in the Content Management System by importing content from other DLS courses."
        );

        public static RadiosListItemViewModel CmsManagerRadioButton = new RadiosListItemViewModel(
            ContentManagementRole.CmsManager,
            "CMS manager",
            "Can create courses in the Content Management System by uploading local digital learning content."
        );
    }
}

DigitalLearningSolutions.Web/ViewModels/TrackingSystem/Centre/Administrator/AdministratorsViewModelFilterOptions.cs
namespace DigitalLearningSolutions.Web.ViewModels.TrackingSystem.Centre.Administrator
{
    using System.Collections.Generic;
    using System.Linq;
    using DigitalLearningSolutions.Data.Enums;
    using DigitalLearningSolutions.Data.Helpers;
    using DigitalLearningSolutions.Data.Models.Common;
    using DigitalLearningSolutions.Data.Models.SearchSortFilterPaginate;
    using DigitalLearningSolutions.Data.Models.User;
    using DigitalLearningSolutions.Web.Helpers.FilterOptions;
    using DigitalLearningSolutions.Web.Models.Enums;
    using DigitalLearningSolutions.Web.ViewModels.Common.SearchablePage;

    public static class AdministratorsViewModelFilterOptions
    {
        public static readonly IEnumerable<FilterOptionModel> RoleOptions = new[]
        {
            AdminRoleFilterOptions.CentreManager,
            AdminRoleFilterOptions.CentreAdministrator,
            AdminRoleFilterOptions.Supervisor,
            AdminRoleFilterOptions.NominatedSupervisor,
            AdminRoleFilterOptions.Trainer,
            AdminRoleFilterOptions.ContentCreatorLicense,
            AdminRoleFilterOptions.CmsAdministrator,
            AdminRoleFilterOptions.CmsManager,
        };

        public static readonly IEnumerable<FilterOptionModel> AccountStatusOptions = new[]
        {
            AdminAccountStatusFilterOptions.IsLocked,
            AdminAccountStatusFilterOptions.IsNotLocked,
        };

        public static IEnumerable<FilterOptionModel> GetCategoryOptions(IEnumerable<string> categories)
        {
            return categories.Select(
                c => new FilterOptionModel(
                    c,
                    nameof(AdminEntity.CategoryName) + FilteringHelper.Separator + nameof(AdminEntity.CategoryName) +
                    FilteringHelper.Separator + c,
                    FilterStatus.Default
                )
            );
        }

        public static List<FilterModel> GetAllAdministratorsFilterModels(IEnumerable<Category> categories)
        {
            var categoryStrings = categories.Select(c => c.CategoryName);
            categoryStrings = categoryStrings.Prepend("All");
            var filters = new List<FilterModel>
            {
                new FilterModel("Role", "Role", RoleOptions),
                new FilterModel(
                    "CategoryName",
                    "Category",
                    GetCategoryOptions(categoryStrings)
                ),
                new FilterModel(
                    "AccountStatus",
                    "Account Status",
                    AccountStatusOptions
                ),
            };
            return filters;
        }
    }
}

DigitalLearningSolutions.Web/Controllers/FindYourCentreController.cs
namespace DigitalLearningSolutions.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using DigitalLearningSolutions.Data.DataServices;
    using DigitalLearningSolutions.Data.Enums;
    using DigitalLearningSolutions.Data.Helpers;
    using DigitalLearningSolutions.Data.Models.SearchSortFilterPaginate;
    using DigitalLearningSolutions.Web.Attributes;
    using DigitalLearningSolutions.Web.Helpers;
    using DigitalLearningSolutions.Web.Models.Enums;
    using DigitalLearningSolutions.Web.Services;
    using DigitalLearningSolutions.Web.ViewModels.FindYourCentre;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Configuration;
    using Microsoft.FeatureManagement;

    [SetDlsSubApplication(nameof(DlsSubApplication.Main))]
    [SetSelectedTab(nameof(NavMenuTab.FindYourCentre))]
    [RedirectDelegateOnlyToLearningPortal]
    public class FindYourCentreController : Controller
    {
        private const string FindCentreFilterCookieName = "FindCentre";
        private readonly ICentresService centresService;
        private readonly IRegionDataService regionDataService;
        private readonly ISearchSortFilterPaginateService searchSortFilterPaginateService;
        private readonly IConfiguration configuration;
        private readonly IFeatureManager featureManager;

        public FindYourCentreController(
            ICentresService centresService,
            IRegionDataService regionDataService,
            ISearchSortFilterPaginateService searchSortFilterPaginateService,
            IConfiguration configuration,
            IFeatureManager featureManager
        )
        {
            this.centresService = centresService;
            this.regionDataService = regionDataService;
            this.searchSortFilterPaginateService = searchSortFilterPaginateService;
            this.configuration = configuration;
            this.featureManager = featureManager;
        }

        [Route("FindYourCentre/{page=1:int}")]
        public async Task<IActionResult> Index(
            int page = 1,
            string? searchString = null,
            string? existingFilterString = null,
            string? newFilterToAdd = null,
            bool clearFilters = false,
            int? itemsPerPage = null
        )
        {
            if (!await featureManager.IsEnabledAsync(FeatureFlags.RefactoredFindYourCentrePage))
            {
                var model = new FindYourCentreViewModel(configuration);

                return View("Index", model);
            }

            existingFilterString = FilteringHelper.GetFilterString(
                existingFilterString,
                newFilterToAdd,
                clearFilters,
                Request,
                FindCentreFilterCookieName
            );

            var centreSummaries = centresService.GetAllCentreSummariesForFindCentre();
            var regions = regionDataService.GetRegionsAlphabetical();

            var availableFilters = FindYourCentreViewModelFilterOptions
                .GetFindCentreFilterModels(regions).ToList();

            var searchSortPaginationOptions = new SearchSortFilterAndPaginateOptions(
                new SearchOptions(searchString, searchMatchCutoff: 90),
                null,
                new FilterOptions(
                    existingFilterString,
                    availableFilters
                ),
                new PaginationOptions(page, itemsPerPage)
            );

            var result = searchSortFilterPaginateService.SearchFilterSortAndPaginate(
                centreSummaries,
                searchSortPaginationOptions
            );

            var refactoredModel = new RefactoredFindYourCentreViewModel(
                result,
                availableFilters
            );

            Response.UpdateFilterCookie(FindCentreFilterCookieName, result.FilterString);

            return View("RefactoredFindYourCentre", refactoredModel);
        }

        public IActionResult CentreData()
        {
            var centres = centresService.GetAllCentreSummariesForMap();
            return Json(centres);
        }
    }
}

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/EditCentreDetails.cshtml
@using DigitalLearningSolutions.Web.ViewModels.TrackingSystem.Centre.Configuration
@model EditCentreDetailsViewModel

<link rel="stylesheet" href="@Url.Content("~/css/trackingSystem/centreConfiguration.css")" asp-append-version="true">

@{
  var errorHasOccurred = !ViewData.ModelState.IsValid;
  ViewData["Title"] = errorHasOccurred ? "Error: Edit centre details" : "Edit centre details";
  const string hintText = @"To change your {0}, select a new image and click the Preview button to preview it.
                    To remove your {0} click the remove button.
                    Changes will not be made until the Save button below is clicked.";
}

<div class="nhsuk-grid-row">
  <div class="nhsuk-grid-column-full">
    @if (errorHasOccurred)
    {
      <vc:error-summary order-of-property-names="@(new[] { nameof(Model.NotifyEmail), nameof(Model.BannerText), nameof(Model.CentreSignatureFile), nameof(Model.CentreLogoFile) })" />
    }

    <h1 class="nhsuk-heading-xl">Edit centre details</h1>
    <form class="nhsuk-u-margin-bottom-3" method="post" novalidate asp-action="EditCentreDetails" enctype="multipart/form-data">
      <div class="hidden-submit">
        <button name="action" class="nhsuk-button" value="save" aria-hidden="true" tabindex="-1">Save</button>
      </div>

      <div class="nhsuk-grid-row divider">
        <div class="nhsuk-grid-column-full">
          <vc:text-input asp-for="NotifyEmail"
                         label="Notify email"
                         populate-with-current-value="true"
                         type="text"
                         spell-check="false"
                         autocomplete="email"
                         hint-text=""
                         css-class="nhsuk-u-width-one-half"
                         required="true" />

          <vc:text-input asp-for="BannerText"
                         label="Centre support details"
                         populate-with-current-value="true"
                         type="text"
                         spell-check="true"
                         autocomplete="off"
                         hint-text=""
                         css-class="nhsuk-u-width-one-half"
                         required="true" />
        </div>
      </div>

      <div class="nhsuk-grid-row nhsuk-u-margin-bottom-2">
        <div class="nhsuk-grid-column-one-half">
          <input type="hidden" aria-hidden="true" asp-for="CentreSignature" />
          <vc:file-input asp-for="CentreSignatureFile" label="Centre signature" hint-text="@string.Format(hintText, "signature")" css-class="nhsuk-u-width-full" />
        </div>
        <div class="nhsuk-grid-column-one-half">
          @if (Model.CentreSignature != null)
          {
            <img class="nhsuk-image__img centre-detail-image__downsize" src="data:image;base64,@Convert.ToBase64String(Model.CentreSignature)" alt="Centre signature picture" />
          }
          else
          {
            <img class="nhsuk-image__img centre-detail--placeholder-image__downsize" src="@Url.Content("~/images/imagePlaceholder.svg")" alt="Placeholder signature image" />
          }
        </div>
      </div>

      <div class="nhsuk-grid-row divider">
        <div class="nhsuk-grid-column-one-half">
          <button name="action" class="nhsuk-button" value="previewSignature">Preview</button>
          <button name="action" class="nhsuk-button nhsuk-button--secondary" value="removeSignature">Remove</button>
        </div>
      </div>

      <div class="nhsuk-grid-row nhsuk-u-margin-bottom-2">
        <div class="nhsuk-grid-column-one-half">
          <input type="hidden" aria-hidden="true" asp-for="CentreLogo" />
          <vc:file-input asp-for="CentreLogoFile" label="Centre logo" hint-text="@string.Format(hintText, "logo")" css-class="nhsuk-u-width-full" />
        </div>
        <div class="nhsuk-grid-column-one-half">
          @if (Model.CentreLogo != null)
          {
            <img class="nhsuk-image__img centre-detail-image__downsize" src="data:image;base64,@Convert.ToBase64String(Model.CentreLogo)" alt="Centre logo picture" />
          }
          else
          {
            <img class="nhsuk-image__img centre-detail--placeholder-image__downsize" src="@Url.Content("~/images/imagePlaceholder.svg")" alt="Placeholder logo image" />
          }
        </div>
      </div>

      <div class="nhsuk-grid-row divider">
        <div class="nhsuk-grid-column-one-half">
          <button name="action" class="nhsuk-button" value="previewLogo">Preview</button>
          <button name="action" class="nhsuk-button nhsuk-button--secondary" value="removeLogo">Remove</button>
        </div>
      </div>

      <button name="action" class="nhsuk-button" value="save">Save</button>
    </form>

    <vc:cancel-link asp-controller="Configuration" asp-action="Index" />

  </div>
</div>

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/EditCentreManagerDetails.cshtml
@using DigitalLearningSolutions.Web.ViewModels.TrackingSystem.Centre.Configuration
@model EditCentreManagerDetailsViewModel

@{
  var errorHasOccurred = !ViewData.ModelState.IsValid;
  ViewData["Title"] = errorHasOccurred ? "Error: Edit centre manager details" : "Edit centre manager details";
}

<div class="nhsuk-grid-row">
  <div class="nhsuk-grid-column-full">
    @if (errorHasOccurred)
    {
      <vc:error-summary order-of-property-names="@(new[] { nameof(Model.FirstName), nameof(Model.LastName), nameof(Model.Email), nameof(Model.Telephone) })" />
    }

    <h1 class="nhsuk-heading-xl">Edit centre manager details</h1>
    <form class="nhsuk-u-margin-bottom-3" method="post" novalidate asp-action="EditCentreManagerDetails">

      <vc:text-input asp-for="FirstName"
                     label="First name"
                     populate-with-current-value="true"
                     type="text"
                     spell-check="false"
                     autocomplete="given-name"
                     hint-text=""
                     css-class="nhsuk-u-width-one-half"
                     required="true" />

      <vc:text-input asp-for="LastName"
                     label="Last name"
                     populate-with-current-value="true"
                     type="text" spell-check="false"
                     autocomplete="family-name"
                     hint-text=""
                     css-class="nhsuk-u-width-one-half"
                     required="true" />

      <vc:text-input asp-for="Email"
                     label="Email"
                     populate-with-current-value="true"
                     type="text"
                     spell-check="false"
                     autocomplete="email"
                     hint-text=""
                     css-class="nhsuk-u-width-one-half"
                     required="true" />

      <vc:text-input asp-for="Telephone"
                     label="Telephone (optional)"
                     populate-with-current-value="true"
                     type="text"
                     spell-check="false"
                     autocomplete=""
                     hint-text=""
                     css-class="nhsuk-u-width-one-half"
                     required="false" />

      <button class="nhsuk-button" type="submit" value="save">Save</button>
    </form>

    <vc:cancel-link asp-controller="Configuration" asp-action="Index" />

  </div>
</div>

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/Index.cshtml
@using DigitalLearningSolutions.Web.Models.Enums
@using DigitalLearningSolutions.Web.ViewModels.TrackingSystem.Centre.Configuration
@model CentreConfigurationViewModel

<link rel="stylesheet" href="@Url.Content("~/css/trackingSystem/centreConfiguration.css")" asp-append-version="true">

@{
  ViewData["Title"] = "Centre configuration";
}

<div class="nhsuk-grid-row">
  <div class="nhsuk-grid-column-one-quarter">
    <nav class="side-nav-menu" aria-label="Side navigation bar">
      <partial name="~/Views/TrackingSystem/Centre/Shared/_CentreSideNavMenu.cshtml" model="CentrePage.Configuration" />
    </nav>
  </div>

  <div class="nhsuk-grid-column-three-quarters">
    <h1 id="page-heading" class="nhsuk-heading-xl">@ViewData["Title"]</h1>

    <div class="nhsuk-card nhsuk-u-margin-top-8 nhsuk-u-margin-bottom-8">
      <div class="nhsuk-card__content basic-card-content">
        <dl class="nhsuk-summary-list">
          <div class="nhsuk-summary-list__row basic-summary-list__row">
            <dt class="nhsuk-summary-list__key">Centre name</dt>
            <dd class="nhsuk-summary-list__value ">@Model.CentreName</dd>
          </div>
          <div class="nhsuk-summary-list__row basic-summary-list__row">
            <dt class="nhsuk-summary-list__key">Region</dt>
            <dd class="nhsuk-summary-list__value ">@Model.RegionName</dd>
          </div>
        </dl>
      </div>
    </div>

    <partial name="_CentreConfigurationCentreDetails" model="Model" />

    <partial name="_CentreConfigurationCentreManagerDetails" model="Model" />

    <partial name="_CentreConfigurationCentreContentDetails" model="Model" />

    <a class="nhsuk-button" role="button" asp-controller="RegistrationPrompts" asp-action="Index">Manage registration prompts</a>

    <nav class="side-nav-menu-bottom" aria-label="Bottom navigation bar">
      <partial name="~/Views/TrackingSystem/Centre/Shared/_CentreSideNavMenu.cshtml" model="CentrePage.Configuration" />
    </nav>
  </div>
</div>

DigitalLearningSolutions.Web/Views/TrackingSystem/Centre/Configuration/_CentreConfigurationCentreContentDetails.cshtml
@using DigitalLearningSolutions.Web.ViewModels.TrackingSystem.Centre.Configuration
@model CentreConfigurationViewModel

@{
  var showCentreOnMap = Model.ShowCentreOnMap ? "Yes" : "No";
}

<details class="nhsuk-details nhsuk-expander nhsuk-u-margin-bottom-8">
  <summary class="nhsuk-details__summary">
    <span class="nhsuk-details__summary-text">
      Centre content on DLS website
    </span>
  </summary>
  <div class="nhsuk-details__text">
    <p>The details below are published on the Digital Learning Solutions website.</p>

    <dl class="nhsuk-summary-list details-list-with-button">
      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Centre telephone
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.CentreTelephone" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Centre email
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.CentreEmail" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Centre postcode
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.CentrePostcode" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Show centre on map
        </dt>
        <partial name="_SummaryFieldValue" model="@showCentreOnMap" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Opening hours
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.OpeningHours" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Centre web address
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.CentreWebAddress" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Organisations covered
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.OrganisationsCovered" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Training venues
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.TrainingVenues" />
      </div>

      <div class="nhsuk-summary-list__row details-list-with-button__row">
        <dt class="nhsuk-summary-list__key">
          Other information
        </dt>
        <partial name="_SummaryFieldValue" model="@Model.OtherInformation" />
      </div>
    </dl>

    <a class="nhsuk-button nhsuk-u-margin-right-2" role="button" asp-action="EditCentreWebsiteDetails">
      Edit
    </a>
    @if (Model.ShowCentreOnMap)
    {
      <a class="nhsuk-button nhsuk-button--secondary" role="button" asp-controller="FindYourCentre" asp-action="Index" asp-route-centreId="@Model.CentreId">
        Preview on website
      </a>
    }

  </div>
</details>